name: Build tvOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-tvos:
    name: Build tvOS IPA
    runs-on: macos-latest
    env:
      scheme: HDrezkaTV
      archive_path: archive

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Archive
        run: |
          xcodebuild archive \
            -archivePath "$archive_path" \
            -scheme "$scheme" \
            -project HDrezka.xcodeproj \
            -sdk appletvos -arch arm64 \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        run: |
          mkdir Payload
          cp -R "$archive_path.xcarchive/Products/Applications/HDrezka.app" Payload/
          zip -r "$scheme.ipa" Payload -x "._*" -x ".DS_Store" -x "__MACOSX"
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v7
        with:
          name: HDrezkaTV.ipa
          path: HDrezkaTV.ipa